### PR TITLE
Implement expenditure import

### PR DESCRIPTION
**Pull request by hancush**
## Overview

This PR extends the contribution import to also import expenditures. It also updates the Makefile recipes to import either type from a local file or S3.

## Testing Instructions

* View the deploy preview and confirm it contains data from before and after 2020.
* Click around and confirm you don't see any Python errors.
* Note in your review any issues you notice. I'll create a bug hunt PR separately.

### CODE REVIEW

**Comment by derekeder** [comment]
a few observations from clicking around:

- found 1 error so far: https://openness-pro-hcg-exp-s43eps6ml.herokuapp.com/candidates/julia-ruiz/

- on the candidate page, the range of the charts are inconsistent. net funds ends in 2020, but donations/expenditures go through 2023. is this expected?

Screenshot 2023-12-07 at 3 39 05 PM

- I see the duplicate organization/candidate issue you mentioned. clicking on candidate pages on the home page, none of them have any net funds or donations/expenditures after June 2020. if I click through donations, it does take me to candidate pages that have 2023 data. however, I can't find an example (yet) with data from before 2020 AND after. They seem to be completely separate. Do we have a way to reconcile them?

These candidates look to be for the same person:

https://openness-pro-hcg-exp-s43eps6ml.herokuapp.com/candidates/michelle-lujan-grisham-2243/
https://openness-pro-hcg-exp-s43eps6ml.herokuapp.com/candidates/michelle-lujan-grisham/

As do these:

https://openness-pro-hcg-exp-s43eps6ml.herokuapp.com/candidates/hector-balderas-3046/
https://openness-pro-hcg-exp-s43eps6ml.herokuapp.com/candidates/hector-balderas/

- seeing many examples of possible duplicate donations:
https://openness-pro-hcg-exp-s43eps6ml.herokuapp.com/donations/?from=2023-10-01&to=2023-11-13&page=2

Screenshot 2023-12-07 at 3 55 03 PM

**Comment by derekeder** [comment]
Nice! The duplicates and errors I saw in my last review are resolved.

Seeing some other things that raise my eyebrows:

Home page title says 'Lobbyist Portal' when I think we are hiding that part.

Screenshot 2023-12-13 at 3 31 52 PM


Hector Balderas has campaigns after 2020, but no financial data after 2020. He also stopped being recognized as a (D): https://openness-pro-hcg-exp-s43eps6ml.herokuapp.com/candidates/hector-balderas-3046/

Screenshot 2023-12-13 at 3 30 00 PM


Of the top 10 Committees, only one has contributions after 2020. Does this mean the old ones don't exist in the new system? Or were they renamed? Is it accurate to show committees in the top 10 (based on cash-on-hand) if we don't have recent data for them?

Screenshot 2023-12-13 at 3 35 16 PM

**Comment by hancush** [comment]
@derekeder tl;dr - The issues you pointed out have to do with missing data or are unrelated. Can this be staged and these issues addressed separately?

> Home page title says 'Lobbyist Portal' when I think we are hiding that part.

This is not relevant to these changes. Can I address this separately?

> Hector Balderas has campaigns after 2020, but no financial data after 2020. He also stopped being recognized as a (D): https://openness-pro-hcg-exp-s43eps6ml.herokuapp.com/candidates/hector-balderas-3046/

This is a product of Office information missing from contribution and expenditure data, which we'll have to address separately. I've already opened a thread with Marjorie about how to handle this.

> Of the top 10 Committees, only one has contributions after 2020. Does this mean the old ones don't exist in the new system? Or were they renamed? Is it accurate to show committees in the top 10 (based on cash-on-hand) if we don't have recent data for them?

I didn't import 2021 or 2022 data, to save time. This will likely change once that comes in. Otherwise, a great question for Marjorie.

**Review by derekeder — APPROVED** [review]
ok, if you want to address those issues in separate PRs, i'm good to bring this in

**Pull request merged**
